train-with-tta:
	python multilabel_train.py -f 0 -w best_weights.pth
	python multilabel_train.py -f 1 -w best_weights.pth
	python multilabel_train.py -f 2 -w best_weights.pth
	python multilabel_train.py -f 3 -w best_weights.pth
	python multilabel_train.py -f 4 -w best_weights.pth